### ISSUE TITLE
UsefulBuf.h gives warnings when used with MSVC

### ISSUE THREAD

**Issue by dthaler** [laurencelundblade/QCBOR#152]
UsefulBuf.h(677,9): warning C4068: unknown pragma 'GCC'
UsefulBuf.h(678,9): warning C4068: unknown pragma 'GCC'
UsefulBuf.h(680,9): warning C4068: unknown pragma 'GCC'
UsefulBuf.h(1760,9): warning C4068: unknown pragma 'GCC'
UsefulBuf.h(1761,9): warning C4068: unknown pragma 'GCC'
UsefulBuf.h(1763,9): warning C4068: unknown pragma 'GCC'

Any GCC pragmas should be inside something like
#ifdef __GNUC__
...
#endif

**Comment by laurencelundblade** [comment]
Hi Dave -- it was left like this because llvm/clang and all the variants from ARM, Nvidia and such based on it also support these pragmas. Will see what I can do...

**Comment by laurencelundblade** [comment]
Thanks for the PR!

**Comment by laurencelundblade** [comment]
Why can't I close this?

**Comment by laurencelundblade** [comment]
Can I close using Firefox?
