### ISSUE TITLE
Need BKM to use CBOR

### ISSUE THREAD

**Issue by AshrafAliS** [laurencelundblade/QCBOR#163]
Hi., I'm looking for best known method for CBOR.

use case. i have a large structure,  and i wanted to convert that structure to CBOR binary,
during the runtime i can locate the buffer and i can get the data.

**Comment by laurencelundblade** [comment]
Well, um there's no CBOR system/protocol design service available here. :-)

If you haven't seen it already, the example source files output and decode a small structure. They could maybe get you started.

**Comment by laurencelundblade** [comment]
No further comments. Closing this issue.
