### ISSUE TITLE
License file/Github setting

### ISSUE THREAD

**Issue by ezelkow1** [laurencelundblade/QCBOR#182]
Would there be a way to have a license set in github and/or a license file created? Just integrating this for use with another spec's library I am writing and plan on opensourcing that, and this is a dependency of it so our corporate open sourcing team was just asking if a license can be added here for easier reference and for their usage

**Comment by laurencelundblade** [comment]
Yes, I think so. Will look into it in the next week or so.

**Comment by laurencelundblade** [comment]
This is fixed in the head of master branch now. I will eventually make a 1.3 release with this and other fixes.

Very very sorry it took so long.
