### ISSUE TITLE
Provide access to underlying encoded buffers

### ISSUE THREAD

**Issue by BrianSipos** [laurencelundblade/QCBOR#248]
I have a need to access the original buffer from an associated `QCBOREncodeContext` and `QCBORDecodeContext` and would prefer to not need to pass around the context _and_ its associated buffer. Instead it would be convenient to be able to access the buffer from an active context. I am currently using the 'private' fields of the context to get the buffer but would rather use a public, stable, and documented function to get access.

**Comment by laurencelundblade** [comment]
Makes sense given some of the other things you've asked for.

**Comment by laurencelundblade** [comment]
Address in QCBOR v1.5
