### ISSUE TITLE
CBOR Canonical Encoding

### ISSUE THREAD

**Issue by joshblum** [laurencelundblade/QCBOR#47]
The documentation says the all of RFC 7049 is supported except strict mode, however I don't see any code to support sorting of map keys according to [section 3.9 of the RFC](https://tools.ietf.org/html/rfc7049#section-3.9). Am I incorrectly using things or is this case not covered. Could you provide a short example if it is? Thanks!

**Comment by laurencelundblade** [comment]
Latest push with spiffy decode clearly says map sorting is not supported. 

Open #52 to eventually actually add the support.
