### ISSUE TITLE
QCBOR_Int64ToUInt64 returns -1

### ISSUE THREAD

**Issue by SebDE** [laurencelundblade/QCBOR#48]
The helper function QCBOR_Int64ToUInt64 in `qcbor_decode.h`

```
static inline int QCBOR_Int64ToUInt64(int64_t src, uint64_t *dest)
{
   if(src > 0) {
      return -1;
   } else {
      *dest = (uint64_t) src;
   }
   return 0;
}
```

return -1 for positive int64_t. Is it possible that the first check is just in den wrong direction?
**if(src < 0)** should do the trick? Or maybe I understand something wrong.

Thanks for a short feedback and many thanks for this great library.

**Comment by laurencelundblade** [comment]
Fixed with https://github.com/laurencelundblade/QCBOR/commit/e15326f502fdc43450e228deb64c51b4e83bf801. Thanks for point it out. Sorry for the bug and lack of tests.
