### ISSUE TITLE
QCBOREncode_Init buffer

### ISSUE THREAD

**Issue by janemba** [laurencelundblade/QCBOR#62]
Hi,

This is not an issue but I don't know where I can ask question about the API.

So I  am trying to use qcbor using a simple structure but it's difficult to understand how the API works just by reading the source. I'm stuck in the beginning with the second parameter of _QCBOREncode_Init_ function.

This parameter is supposed to be the buffer after encoding. Looking at _example.c_ and _test/qcbor_encode_tests.c_ the size of the buffer doesn't seem to be calculated. For one case, the declaration is `static uint8_t spBigBuf[2200]` and for the other case `MakeUsefulBufOnStack(   EngineBuffer, 300)`.

Is there a way to give the real size for the buffer ?

I have another question. In which case should I use `MakeUsefulBufOnStack` or `UsefulBuf_FROM_BYTE_ARRAY` ?

**Comment by laurencelundblade** [comment]
See if the improved documentation and sample code from #65 helps this for you. 

Appreciate the comment!
