### ISSUE TITLE
determine how much of a buffer was decoded

### ISSUE THREAD

**Issue by mcr** [laurencelundblade/QCBOR#76]
Given that struct _QCBORDecodeContext is supposed to be private, is there a way to find out how many bytes from an input buffer were consumed?  So that after processing one CBOR item from a stream, I know how far to advance my pointer to process the next chunk.
Yes, if I keep the QCBORDecodeContext around, then I can just continue, but in some cases I want to hide that part.

**Comment by laurencelundblade** [comment]
See if PR #77 works for you.

The PR needs a little more testing, spell checks and such before merge to main, but it seems close.
